account/urls.py
from django.urls import path

from account.views import (
	account_view,
    edit_account_view,
    # edit_pass_view,
    tokenSend,
    verify,
    nearby_uni,
    registration_error,
    nearby_uni_stud,
    prompt_view,
    resend_verif_view,
    
)

app_name = 'account'

urlpatterns = [
	path('<user_id>/', account_view, name="view"),
    path('<user_id>/edit/', edit_account_view, name='edit'),
    # path('<user_id>/edit-pass/', edit_pass_view, name='edit-pass'),

	path('register/token/', tokenSend, name="token"),
    path('verify/<auth_token>' , verify , name="verify"),
    path('nearby/universities' , nearby_uni , name="nearby-uni"),
    path('nearby/uni-students/<uni_id>' , nearby_uni_stud , name="nearby-uni-stud"),
    path('registration/issueForm' , registration_error , name="reg-error"),
    path('prompt/view' , prompt_view , name="prompt"),
    path('resend/verification_email' , resend_verif_view , name="resend-verif"),
    
    
]

friend/urls.py
from django.urls import path

from friend.views import(
	send_friend_request,
    friend_requests,
    accept_friend_request,
    remove_friend,
    decline_friend_request,
    cancel_friend_request,
    friends_list_view
)

app_name = 'friend'

urlpatterns = [
    path('friend_requests/<user_id>/', friend_requests, name='friend-requests'),
    path('list/<user_id>', friends_list_view, name='list'),

    path('friend_request/', send_friend_request, name='friend-request'),
    path('friend_request_accept/<friend_request_id>/', accept_friend_request, name='friend-request-accept'),

    path('friend_remove/', remove_friend, name='remove-friend'),
    path('friend_request_decline/<friend_request_id>/', decline_friend_request, name='friend-request-decline'),
    path('friend_request_cancel/', cancel_friend_request, name='friend-request-cancel'),
]

mystranger/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from mystranger_app.views import *
from account.views import (
    register_view,
    login_view,
    logout_view,
    account_search_view,
)

from nrt.views import *
from qna.views import *
from django.views.generic import TemplateView

handler404 = 'mystranger_app.views.error_404_view'

urlpatterns = [
    path('evilstranger666/', admin.site.urls),
    path('home/', home_view, name='home' ),
    path('', new_home_view, name='new-home' ),
    path('new_chat/', new_chat_view , name='new-chat' ),
    path('new_chat_text/', new_chat_text_view , name='new-chat-text' ),
    path('nrt_text/', nrt_text_view , name='nrt-text' ),
    path('nrt_text/how', nrt_text_how_view , name='nrt-text-how' ),
    path('nrt_text/wow', nrt_text_wow_view , name='nrt-text-wow' ),

    # path('notif-token/', save_token, name="notif-token"),
    path('notif-token/', notif_token_view, name="notif-token"),
    path('firebase-messaging-sw.js', service_worker, name='service_worker'),

    # path('send_push', send_push),
    # path('webpush/', include('webpush.urls')),
    # path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript')),
    # path('firebase-messaging-sw.js/',showFirebaseJS,name="show_firebase_js"),


    path('search/', account_search_view, name="search"),
    path('feedback/', feedback_view, name="feedback"),
    path('privacy_policy/', privacy_policy_view, name="privacy-policy"),
    path('delete_account/', delete_account_view, name="delete-account"),
    path('aboutus/', aboutus_view, name="about-us"),
    path('terms/', terms_view, name="terms-conditions"),
    
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),

    path('account/', include('account.urls', namespace='account')),
    path('vibes/', include('qna.urls', namespace='qna')),
    path('confessions/', include('confessions.urls', namespace='confessions')),

    # Friend System
    path('friend/', include('friend.urls', namespace='friend')),

    # Public Chat App
    path('chat/', include('chat.urls', namespace='chat')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
         name='password_change'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset/password_reset_form.html'), name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
    name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset/password_reset_change_form.html'), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
    name='password_reset_complete'),

    # -------------------------------------
    

]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    

qna/urls.py
from django.urls import path
from qna.views import *

app_name = 'qna'

urlpatterns = [
    path('', pika_view , name='pika' ),
    path('create_post/', create_post_view, name='create-post'),
    path('minichat/<user_id>/', minichat_view , name='minichat' ),
    path('addAnswer/', addAnswer_view , name='addAnswer' ),
    path('question/<ans_id>/', show_ques_view , name='question-view' ),
]

friend/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
import json
from django.db.models import Q

from account.models import Account
from friend.models import FriendRequest, FriendList
from django.utils import timezone
from datetime import timedelta
from django.views.decorators.csrf import csrf_exempt

def friends_list_view(request, *args, **kwargs):
	context = {}
	user = request.user
	if user.is_authenticated:
		user_id = kwargs.get("user_id")
		if user_id:
			try:
				this_user = Account.objects.get(pk=user_id, is_verified = True)
				context['this_user'] = this_user
			except Account.DoesNotExist:
				return HttpResponse("That user does not exist.")
			try:
				friend_list = FriendList.objects.get(user=this_user)
			except FriendList.DoesNotExist:
				return HttpResponse(f"Could not find a friends list for {this_user.name}")
			
			# Must be friends to view a friends list
			if user != this_user:
					return HttpResponse("You can not view other people's friend list")
			friends = [] # [(friend1, True), (friend2, False), ...]
			# get the authenticated users friend list
			# auth_user_friend_list = FriendList.objects.get(user=user)
			for friend in friend_list.friends.all():
				friends.append((friend, True))
			context['friends'] = friends
	else:		
		return HttpResponse("You must be friends to view their friends list.")
	return render(request, "friend/friend_list.html", context)

def friend_requests(request, *args, **kwargs):
	context = {}
	try:
		user = request.user
		if user.is_authenticated:
			user_id = kwargs.get("user_id")
			account = Account.objects.get(pk=user_id, is_verified = True)
			if account == user:
				friend_requests = FriendRequest.objects.filter(receiver=account, is_active=True)
				if friend_requests.exists():
					context['friend_requests'] = friend_requests
			else:
				return HttpResponse("You can't view another users friend requets.")
		else:
			return redirect("login")
	except Exception as e:
		print(e)
	return render(request, "friend/friend_requests.html", context)

@csrf_exempt
def send_friend_request(request, *args, **kwargs):
	user = request.user
	payload = {}
	if request.method == "POST" and user.is_authenticated:
		user_id = request.POST.get("receiver_user_id")
		if user_id:
			receiver = Account.objects.get(pk=user_id, is_verified = True)
			try:
				# Get any friend requests (active and not-active)
				friend_requests = FriendRequest.objects.filter(sender=user, receiver=receiver)
				# find if any of them are active (pending)
				try:
					for request in friend_requests:
						if request.is_active:
							raise Exception("You already sent them a friend request.")
						
					# check if you are already friends or not -
					friend_list = FriendList.objects.filter(user=user).first()
					is_already_friend = friend_list.is_mutual_friend(receiver)
					if is_already_friend:
						raise Exception("You are already friends with them.")
					
					# A user can only send 10 friend requests in 24 hrs
					"""
					Gotta find a way to make this work ...
					"""
					# all_friend_requests = FriendRequest(sender=user, receiver=receiver)
					 # Calculate the timestamp for 24 hours ago
					# twenty_four_hours_ago = timezone.now() - timedelta(hours=12)

					# # Query for friend requests sent by the user in the past 24 hours
					# sent_requests = FriendRequest.objects.filter(
					# 	sender=user,
					# 	timestamp__gte=twenty_four_hours_ago
					# ).order_by('-timestamp')

					# sent_requests_count = sent_requests.count()
					# print('this is the friend req count - ', sent_requests_count)
					# if sent_requests_count > 5:
					# 	raise Exception("To maintain a positive and respectful community, each user is limited to sending a maximum of 5 friend requests within a 12-hour period. This measure is in place to prevent spamming and ensure a quality experience for everyone.  If you have reached the limit, kindly wait for some time before sending additional friend requests.")

					# If none are active create a new friend request
					friend_request = FriendRequest(sender=user, receiver=receiver)
					friend_request.save()
					payload['response'] = "Friend request sent."
				except Exception as e:
					print('we are getting an exceptionhere - ', str(e))
					payload['response'] = str(e)
			except FriendRequest.DoesNotExist:
				# There are no friend requests so create one.
				friend_request = FriendRequest(sender=user, receiver=receiver)
				friend_request.save()
				payload['response'] = "Friend request sent."

			if payload['response'] == None:
				payload['response'] = "Something went wrong."
		else:
			payload['response'] = "Unable to sent a friend request."
	else:
		payload['response'] = "You must be authenticated to send a friend request."
	return HttpResponse(json.dumps(payload), content_type="application/json")

@csrf_exempt
def accept_friend_request(request, *args, **kwargs):
	user = request.user
	payload = {}
	if request.method == "GET" and user.is_authenticated:
		friend_request_id = kwargs.get("friend_request_id")
		if friend_request_id:
			friend_request = FriendRequest.objects.get(pk=friend_request_id)
			# confirm that is the correct request
			if friend_request.receiver == user:
				if friend_request: 
					# found the request. Now accept it
					updated_notification = friend_request.accept()
					payload['response'] = "Friend request accepted."

				else:
					payload['response'] = "Something went wrong."
			else:
				payload['response'] = "That is not your request to accept."
		else:
			payload['response'] = "Unable to accept that friend request."
	else:
		# should never happen
		payload['response'] = "You must be authenticated to accept a friend request."
	return HttpResponse(json.dumps(payload), content_type="application/json")

@csrf_exempt
def remove_friend(request, *args, **kwargs):
	user = request.user
	payload = {}
	if request.method == "POST" and user.is_authenticated:
		user_id = request.POST.get("receiver_user_id")
		if user_id:
			try:
				removee = Account.objects.get(pk=user_id, is_verified = True)
				friend_list = FriendList.objects.get(user=user)
				friend_list.unfriend(removee)
				payload['response'] = "Successfully removed that friend."
			except Exception as e:
				payload['response'] = f"Something went wrong: {str(e)}"
		else:
			payload['response'] = "There was an error. Unable to remove that friend."
	else:
		# should never happen
		payload['response'] = "You must be authenticated to remove a friend."
	return HttpResponse(json.dumps(payload), content_type="application/json")

@csrf_exempt
def decline_friend_request(request, *args, **kwargs):
	user = request.user
	payload = {}
	if request.method == "GET" and user.is_authenticated:
		friend_request_id = kwargs.get("friend_request_id")
		if friend_request_id:
			friend_request = FriendRequest.objects.get(pk=friend_request_id)
			# confirm that is the correct request
			if friend_request.receiver == user:
				if friend_request: 
					# found the request. Now decline it
					updated_notification = friend_request.decline()
					payload['response'] = "Friend request declined."
				else:
					payload['response'] = "Something went wrong."
			else:
				payload['response'] = "That is not your friend request to decline."
		else:
			payload['response'] = "Unable to decline that friend request."
	else:
		# should never happen
		payload['response'] = "You must be authenticated to decline a friend request."
	return HttpResponse(json.dumps(payload), content_type="application/json")

@csrf_exempt
def cancel_friend_request(request, *args, **kwargs):
	user = request.user
	payload = {}
	if request.method == "POST" and user.is_authenticated:
		user_id = request.POST.get("receiver_user_id")
		if user_id:
			receiver = Account.objects.get(pk=user_id, is_verified = True)
			try:
				friend_requests = FriendRequest.objects.filter(sender=user, receiver=receiver, is_active=True)
			except FriendRequest.DoesNotExist:
				payload['response'] = "Nothing to cancel. Friend request does not exist."

			# There should only ever be ONE active friend request at any given time. Cancel them all just in case.
			if len(friend_requests) > 1:
				for request in friend_requests:
					request.cance()
				payload['response'] = "Friend request canceled."
			else:
				# found the request. Now cancel it
				friend_requests.first().cancel()
				payload['response'] = "Friend request canceled."
		else:
			payload['response'] = "Unable to cancel that friend request."
	else:
		# should never happen
		payload['response'] = "You must be authenticated to cancel a friend request."
	return HttpResponse(json.dumps(payload), content_type="application/json")

friend/templates/friend/friend_list.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

<style type="text/css">
	.profile-image{
		max-height: 100px;
		max-width: 100px;
	}
	.profile-image{
		border-radius: 12px;
	}
	.card{
		border-radius: 12px;
	}
	.friends-text{
		color: #000;
		font-weight: 500;
	}
	{% comment %} .friends-text-container{
		border: 1px solid #cccccc;
		border-radius: 12px;
	} {% endcomment %}
	.friends-btn:hover {
		background-color: #bfbfbf;
		border-color: #bfbfbf;
	}
	.dropdown-toggle::after { 
		content: none; 
	}
	.profile-link{
		color: #000;
	}
	.checkmark-icon{
		color: green;
	}
	.cancel-icon{
		color: red;
	}

	.c-main {
        width: 35vw;
        margin: auto;
        margin-top: 5px;
        border: 1px solid #707070;
    }

	.cont1 {
        border-bottom: 2px solid #707070;
        display: flex;
    }

	.name-title {
        font-size: 20px;
    }

	.msg-btn{
        font-size: 15px;
        margin-left: 1em;
    }
	
	/* Media query for tablet width 320px */
  @media only screen and (min-width: 300px) and (max-width: 600px) { 

	.c-main{
		width:unset;
	}

	.cont1{
		flex-direction:column!important;
	}

  }


</style>

<div class="container">
	<div class="card p-2 c-main">

		{% if friends %}
		<div class="d-flex flex-row flex-wrap">
		{% for friend in friends %}
		<div class="cont1 flex-row flex-grow-1 p-2 mx-2 my-2 align-items-center">
			{% comment %} <a class="profile-link" href="{% url 'account:view' user_id=friend.0.pk %}">
				<div class="card-image m-2">
					<img class="img-fluid profile-image" src="{{friend.0.profile_image.url}}" alt="">
				</div>
			</a> {% endcomment %}
			
			<div class="card-center px-2 d-flex">
				<a class="profile-link" href="{% url 'account:view' user_id=friend.0.pk %}">
					<h4 class="name-title">{{friend.0.name|truncatechars:50}}</h4>
				</a>
				{% if friend.1 %}
				{% comment %} <a href="#" onclick="createOrReturnPrivateChat('{{friend.0.id}}')">Send a Message</a> {% endcomment %}
				<a href="#" onclick="createOrReturnPrivateChat('{{friend.0.id}}')"><button class="btn btn-sm btn-outline-dark msg-btn">Message</button></a>
				{% endif %}
				
			</div>
			
			<div class="d-flex flex-row card-right flex-grow-1 justify-content-end mx-2">
				{% if friend.1 %}
					<div class="d-flex flex-row friends-text-container p-2">
						<p class="friends-text m-auto">
							Friends 
						</p>
						<span class="material-icons checkmark-icon m-auto pl-2">
						check_circle_outline
						</span>
					</div>
				{% else %}
					{% if friend.0 !=  request.user %}
						<div class="d-flex flex-row friends-text-container p-3">
							<p class="friends-text m-auto">
								Not Friends 
							</p>
							<span class="material-icons cancel-icon m-auto pl-2">cancel</span>
						</div>
					{% endif %}
				{% endif %}
				{% if friend.0 == request.user %}
					<div class="d-flex flex-row friends-text-container p-3">
						<p class="friends-text m-auto">
							This is you 
						</p>
						<span class="material-icons m-auto pl-2">
						person_pin
						</span>
					</div>
				{% endif %}
			</div>
		</div>
		{% if forloop.counter|divisibleby:1 %}
		</div><div class="d-flex flex-row flex-wrap">
		{% endif %}
		
		{% endfor %}
		
		{% else %} <!-- If no friends -->
		<div class="d-flex flex-row flex-grow-1 justify-content-center align-items-center p-4">
			<p>No friends :(</p>
		</div>
		{% endif %}
		</div>
	</div>
	
</div>

{%  include 'chat/snippets/create_or_return_private_chat.html' %}


{% endblock body %}

friend/templates/friend/friend_requests.html
{% extends 'base.html' %}
{% load static %}

{% block body %}


<style type="text/css">
    .profile-image {
        max-height: 100px;
        max-width: 100px;
    }

    .profile-image {
        border-radius: 12px;
    }

    .card {
        border-radius: 12px;
    }

    .dropdown-toggle::after {
        content: none;
    }

    .profile-link {
        color: #000;
    }

    .material-icons {
        font-size: 30px;
    }

    .material-icons:hover {
        cursor: pointer;
    }

    .confirm-friend-request {
        color: green;
    }

    .confirm-friend-request:hover {
        opacity: 0.3;
    }

    .decline-friend-request:hover {
        opacity: 0.3;
    }

    .decline-friend-request {
        color: red;
    }

    .c-main {
        width: 35vw;
        margin: auto;
        margin-top: 5px;
        border: 1px solid #707070;
    }

    .cont1 {
        border-bottom: 2px solid #707070;
        display: flex;
    }

</style>

<div class="container">
    <div class="card p-2 c-main">

        {% if friend_requests %}
        <div class="d-flex flex-row flex-wrap">
            {% for request in friend_requests %}
            <div class="cont1 flex-row flex-grow-1 p-2 mx-2 my-2 align-items-center">
                {% comment %} <a class="profile-link" href="{% url 'account:view' user_id=request.sender.id %}">
                    <div class="card-image m-2">
                        <img class="img-fluid profile-image" src="{{request.sender.profile_image.url}}" alt="">
                    </div>
                </a> {% endcomment %}
                <a class="profile-link" href="{% url 'account:view' user_id=request.sender.id %}">
                    <div class="card-center px-2">
                        <h4 class="">{{request.sender.name}}</h4>
                    </div>
                </a>
                <div class="d-flex flex-row card-right flex-grow-1 justify-content-end mx-2">
                    <span id="id_cancel_{{request.sender.id}}" class="decline-friend-request material-icons p-1"
                        onclick='triggerDeclineFriendRequest("{{request.id}}")'>cancel</span>
                    <span id="id_confirm_{{request.sender.id}}" class="confirm-friend-request material-icons p-1"
                        onclick='triggerAcceptFriendRequest("{{request.id}}")'>check</span>
                </div>
            </div>
            {% if forloop.counter|divisibleby:2 %}
        </div>
        <div class="d-flex flex-row flex-wrap">
            {% endif %}

            {% endfor %}

            {% else %} <!-- If no friends -->
            <div class="d-flex flex-row flex-grow-1 justify-content-center align-items-center p-4">
                <p>No Friend Requests Found </p>
            </div>
            {% endif %}
        </div>
    </div>

</div>

<script type="text/javascript">

    function onFriendRequestAccepted() {
        location.reload();
    }

    function triggerAcceptFriendRequest(friend_request_id) {
        acceptFriendRequest(friend_request_id, onFriendRequestAccepted)
    }
    
    function onFriendRequestDeclined() {
        location.reload();
    }

    function triggerDeclineFriendRequest(friend_request_id) {
        declineFriendRequest(friend_request_id, onFriendRequestDeclined)
    }

   
</script>

{% include 'friend/snippets/accept_friend_request.html' %}
{% include 'friend/snippets/decline_friend_request.html' %}

{% endblock body %}