confessions/urls.py
from django.urls import path
from confessions.views import *

app_name = 'confessions'

urlpatterns = [
    path('', pikac_view , name='pikac' ),
    path('create_post/', create_post_view, name='create-postc'),
    path('minichat/<user_id>/', minichat_view , name='minichatc' ),
    path('addAnswer/', addAnswer_view , name='addAnswerc' ),
    path('question/<ans_id>/', show_ques_view , name='question-viewc' ),
    path('cworking/', cworking_view , name='cworking' ),
    path('search/', search_view , name='search-view' ),
]

mystranger/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from mystranger_app.views import *
from account.views import (
    register_view,
    login_view,
    logout_view,
    account_search_view,
)

from nrt.views import *
from qna.views import *
from django.views.generic import TemplateView

handler404 = 'mystranger_app.views.error_404_view'

urlpatterns = [
    path('evilstranger666/', admin.site.urls),
    path('home/', home_view, name='home' ),
    path('', new_home_view, name='new-home' ),
    path('new_chat/', new_chat_view , name='new-chat' ),
    path('new_chat_text/', new_chat_text_view , name='new-chat-text' ),
    path('nrt_text/', nrt_text_view , name='nrt-text' ),
    path('nrt_text/how', nrt_text_how_view , name='nrt-text-how' ),
    path('nrt_text/wow', nrt_text_wow_view , name='nrt-text-wow' ),

    # path('notif-token/', save_token, name="notif-token"),
    path('notif-token/', notif_token_view, name="notif-token"),
    path('firebase-messaging-sw.js', service_worker, name='service_worker'),

    # path('send_push', send_push),
    # path('webpush/', include('webpush.urls')),
    # path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript')),
    # path('firebase-messaging-sw.js/',showFirebaseJS,name="show_firebase_js"),


    path('search/', account_search_view, name="search"),
    path('feedback/', feedback_view, name="feedback"),
    path('privacy_policy/', privacy_policy_view, name="privacy-policy"),
    path('delete_account/', delete_account_view, name="delete-account"),
    path('aboutus/', aboutus_view, name="about-us"),
    path('terms/', terms_view, name="terms-conditions"),
    
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),

    path('account/', include('account.urls', namespace='account')),
    path('vibes/', include('qna.urls', namespace='qna')),
    path('confessions/', include('confessions.urls', namespace='confessions')),

    # Friend System
    path('friend/', include('friend.urls', namespace='friend')),

    # Public Chat App
    path('chat/', include('chat.urls', namespace='chat')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
         name='password_change'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset/password_reset_form.html'), name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
    name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset/password_reset_change_form.html'), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
    name='password_reset_complete'),

    # -------------------------------------
    

]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    

qna/urls.py
from django.urls import path
from qna.views import *

app_name = 'qna'

urlpatterns = [
    path('', pika_view , name='pika' ),
    path('create_post/', create_post_view, name='create-post'),
    path('minichat/<user_id>/', minichat_view , name='minichat' ),
    path('addAnswer/', addAnswer_view , name='addAnswer' ),
    path('question/<ans_id>/', show_ques_view , name='question-view' ),
]

confessions/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from confessions.models import CPublicChatRoom, CAnswer
import json
from django.db.models import Count
from django.contrib import messages
from account.models import Account

from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.db.models import Count
from django.template.loader import render_to_string
from django.template import RequestContext
import uuid
from django.utils import timezone
from datetime import timedelta
from django.http import HttpResponseNotFound



# Create your views here.
def pikac_view(request):

    print('confesion is gettin called!')

    # if not request.user.is_authenticated:
    #     return redirect('login')

    if request.user.is_authenticated:
        user = request.user
        user.update_last_activity()

    context = {}
    

    # question_answers = [] # ['{question' : {answers}}]

    # questions = PublicChatRoom.objects.all()
    questions = CPublicChatRoom.objects.all().order_by('-timestamp')
    # questions = PublicChatRoom.objects.all().exclude(answers__user = request.user)
    questions = questions.order_by('-timestamp')

    unpolled_questions = []
    for question in questions:
       
        print('question - ', question)

        '''
        check if the question is already polled than don't show it to the user
        '''
        # skip_outer_loop = False
        # for poll in question.polls.all():
        #     if request.user in poll.polled.all():
        #         # print('The user has already polled this quest &&&&&&&&&&&&&&&')
        #         skip_outer_loop = True
        #         break  # exit the inner loop

        # if skip_outer_loop:
        #     continue  # skip the remaining iterations of the outer loop

        unpolled_questions.append(question)
    
    # Number of questions to display per page
    questions_per_page = 5

    paginator = Paginator(unpolled_questions, questions_per_page)
    page = request.GET.get('page', 1)

    try:
        questions_page = paginator.page(page)
    except PageNotAnInteger:
        # If the page is not an integer, deliver the first page.
        questions_page = paginator.page(1)
    except EmptyPage:
        # If the page is out of range (e.g. 9999), deliver the last page of results.
        questions_page = paginator.page(paginator.num_pages)

    # Access the questions for the current page
    current_page_questions = questions_page.object_list

    context['the_questions'] = questions_page
    # print('this is the questions page - ',current_page_questions)
    my_list = qna_payload(request, current_page_questions)

    # print(my_list)


    # # Your existing code to retrieve questions
    # questions = PublicChatRoom.objects.all().order_by('-timestamp')
    # questions_per_page = 5

    # paginator = Paginator(questions, questions_per_page)
    # page = request.GET.get('page', 1)

    try:
        questions_page = paginator.page(page)
    except PageNotAnInteger:
        questions_page = paginator.page(1)
    except EmptyPage:
        questions_page = paginator.page(paginator.num_pages)

    current_page_questions = questions_page.object_list

    context = {
        'the_questions': questions_page,
    }

    # print('this is the questions page - ',current_page_questions)
    my_list = qna_payload(request, current_page_questions)

    # print(my_list)
    context['question_top2_answers'] = my_list

    if request.GET.get('action') == 'new_ques':
        # If it's an AJAX request, return JSON response
        print('the ajax request is getting processed')
       
        data = {
            'html': render_to_string('confessions/question_partialc.html', {'question_top2_answers': my_list,'the_questions': questions_page}, request=request),
            'has_next': questions_page.has_next(),
        }
        # print('the fuckin data - ', data)
        return JsonResponse(data)

    # for question in questions:
    #     # question_answers.append([question, question.answers.all()])
    #     # print('question - ', question)

    #     '''
    #     check if the question is already polled than don't show it to the user
    #     '''
    #     skip_outer_loop = False
    #     for poll in question.polls.all():
    #         if request.user in poll.polled.all():
    #             # print('The user has already polled this quest &&&&&&&&&&&&&&&')
    #             skip_outer_loop = True
    #             break  # exit the inner loop

    #     if skip_outer_loop:
    #         continue  # skip the remaining iterations of the outer loop

    #     answers_with_descendants = []

    #     answers = question.answers.filter(parent=None).annotate(report_count=Count('ans_reports')).exclude(report_count__gt=10)
    #     answers = answers.annotate(num_likes=Count('likes'))
    #     answers = answers.order_by('-num_likes')[:1]

    #     top2_ans = []
    #     for answer in answers:
    #         # print('The parent answer - ', answer)
            
    #         answers_and_replies = [answer] + list(answer.get_descendants())
    #         answers_with_descendants.extend(answers_and_replies) 
    #         top2_ans.append(answer.pk)
        
    #     # assuming that above instead of sending the first 2 answers we have send the top 2 answers , now we want to send the rest of the answers excluding the above 2

    #     other_answers_with_descendants = []

    #     if not question.polls.all():
    #         answers = question.answers.filter(parent=None).exclude(id__in=top2_ans)
    #     else:
    #         answers = question.answers.filter(parent=None)
    #     answers = answers.order_by('-timestamp')
    #     for answer in answers:
    #         # print('This is what the pending answers are - ', answer)
    #         print('The answer - ',answer,' The reports - ',answer.ans_reports.all().count())
    #         if answer.ans_reports.all().count() < 5:
    #             other_answers_and_replies = [answer] + list(answer.get_descendants())
    #             other_answers_with_descendants.extend(other_answers_and_replies) 
        


        
    #     question_answers.append([question,answers_with_descendants, other_answers_with_descendants])
            
        
   
    # context['question_top2_answers'] = my_list
    context['is_active'] = 'confessions'

    return render(request, "confessions/questions.html", context)

def create_post_view(request):

    if not request.user.is_authenticated:
        return redirect('login')

    if request.method == 'POST':

        user = request.user
        twenty_four_hours_ago = timezone.now() - timedelta(hours=24)

        # Query for confessions sent by the user in the past 24 hours
        sent_requests = CPublicChatRoom.objects.filter(
            owner=user,
            timestamp__gte=twenty_four_hours_ago
        ).order_by('-timestamp')

        confessions_count = sent_requests.count()
        print('this is the friend req count - ', confessions_count)
        if confessions_count > 10:
            messages.warning(request, 'You can only send 10 Tagged confessions in 24 hrs.')
            return redirect('confessions:create-postc')

        question = request.POST.get('question')
        # taggiemail = request.POST.get('taggiemail')
        taggiemail = request.POST.get('taggiemail')
        taggiemode = request.POST.get('selecti')
        taggiename = request.POST.get('taggiename')

        print('the taggie ode - ',taggiemode)
        # print('the taggie info - ',taggieinfo)
        

        # poll1 = request.POST.get('poll1')
        # poll2 = request.POST.get('poll2')
        # poll3 = request.POST.get('poll3')
        # poll4 = request.POST.get('poll4')

        
        if taggiemail:
            confesser_id = my_unique_confession_id(request.user)
            print('This is the confesser id - ', confesser_id)
            roomv = CPublicChatRoom(question = question, owner = user, confesserid = confesser_id)
            

            # generate a unique token so that the taggie can reply back on this confession 
            confession_token = str(uuid.uuid4())
            roomv.taggie_token = confession_token
            roomv.taggie_name = taggiename
            roomv.is_tagged = True

            if taggiemail:
                # later on filter whether its abusive or not but for now just send it -
                '''
                Here we gotta send an email to the taggie at the given info
                ''' 
                roomv.taggie_info = taggiemail
                roomv.taggie_email = taggiemode
                roomv.save()
            

            answer = CAnswer(question = roomv, user = user, content=question, confesserid = confesser_id)
            answer.save()

            # how to generate the link
            mi_tukon = f"https://mystranger.in/confessions/question/{roomv.pk}/?question=true&taggie_token={confession_token}"

            roomv.taggie_link = mi_tukon
            roomv.save()
            
                # save the info into the confesions 
                

        #     #This means this questions has polls in it

        #     polls_list = [poll1,poll2,poll3,poll4]
        #     counter = 0
        #     for poll in polls_list:
        #         if poll:
        #             counter += 1
        #     if counter <2:
        #         messages.warning(request, 'Please add atleast two poles or add none...')
        #         return redirect('confessions:create-post')
        #     roomv = CPublicChatRoom(question = question, owner = user)
        #     roomv.save()
        #     # for poll in polls_list:
        #     #     if poll:
        #     #         pollva = Polls(question = roomv, option=poll)
        #     #         pollva.save()
        
        else:
            confesser_id = my_unique_confession_id(request.user)

confessions/templates/confessions/create_question_main.html
{% extends "base.html" %}

{% block body %}

<style>

  /* Media query for tablet width 320px */
  @media only screen and (min-width: 300px) and (max-width: 600px) { 

    .phone-font{
      font-size:1.2em;
    } 

  }

</style>

{% if messages %}
  
    {% for message in messages %}
      
      <div style="margin-bottom: 0px;" class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong></strong> {{message}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
 
{% endif %}
<div class="p-2 mb-2 bg-body-tertiary rounded-3">
    <div class="container-fluid py-5">
      
      <h4 class="display-8 fw-bold phone-font">Confess anything anonymously-</h4>
      <form action="" method="post"> {% csrf_token %}
      {% comment %} <input type="text"  class="radius form-control" placeholder="Confess without being judged" required
      autofocus> {% endcomment %}
      <textarea name="question" id="question" class="radius form-control" style="font-size:14px;" placeholder="Confess without being judged" cols="30" rows="2" required
      autofocus></textarea>

      <div class="demmo">

        <p class="d-flex gap-1 d-link" style="flex-direction:column; margin-top:8px; font-size:14px;">
					<span>Wanna see what the taggie is gonna recieve - </span>
					<a class="" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
					Show Me
					</a>
					
				</p>
				<div class="collapse" id="collapseExample">
					<div class="d-card" style="font-size:12px;">
            <p>Hi Taggie Name, </p>
            <p>Someone you know has confessed this about you on mystranger.in</p>
            
            "<span id="output"></span>"
            
            <p style="margin-top:6px;"> You can respond to their confession by visiting mystranger.in now. 
            you can only reply to their confession using the below link because it contains your unique token for that particular confession - "https:mystranger.in/confessions/questions/29/?question=True&Taggie_token=Token" </p>
           
					</div>
					
				</div>

      </div>

      {% comment %} polls optional {% endcomment %}
      <h6 class="text-secondary mt-4">Wanna Tag Someone? (optional)</h6>
      <p class="text-secondary mt-2" style="font-size:14px;">No other user can see this information, these are just required to send your anonymous confession to the taggie.</p>
      
      <label class="mt-2" for="taggiename">Taggie Name - </label>
      <input type="text" name="taggiename" id="taggiename" class="radius form-control" placeholder="Taggie Name -">

      <label class="mt-2" for="taggiemail">Taggie Email - </label>
      <input type="email" name="taggiemail" id="taggiemail" class="radius form-control" placeholder="Taggie Email (optional)">
      <p class="text-secondary" style="font-size:12px;">Email is the fastest way to reach that person.</p>


      <label class="" for="taggieinfo">Enter any valid id of the taggie - </label>
      <textarea name="taggieinfo" id="taggieinfo" class="form-control" style="font-size:14px;" placeholder="Enter any valid id of the taggie where mystranger.in can reach them it can be their instagram, snapchat , telegram, discord username etc.. , whatsapp no. or a valid mobile number or anything else where your confession can reach them. Makesure to specify the format - 'whatsapp : 87xxxxxxxx , instagram : Hixxxxx44 , Mobile Number : 87xxxxxxxx , etc ....'" cols="30" rows="5"></textarea>

      <p class="text-secondary mt-2" style="font-size:12px;">You can add multiple id's of the same person (Taggie) to make sure your confession reaches them</p>
      <p class="text-secondary mt-2" style="font-size:12px;">It can take upto 1 hr to 24 hrs for your confession to reach the taggie.</p>
      <button class="btn btn-sm btn-outline-dark mt-4" type="Submit">Submit Confession</button>
    </form>
    </div>
  </div>


  
<script>

   // Get references to the textarea and the output div
   var textarea = document.getElementById('question');
   var outputDiv = document.getElementById('output');

   // Add an event listener for the 'input' event on the textarea
   textarea.addEventListener('input', function() {
       // Update the content of the output div with the textarea's value
       outputDiv.textContent = textarea.value;
   });

  {% comment %} function limitInput(id) {
      var input = document.getElementById(id);
      var charCount = document.getElementById("charCount-"+id);
      var maxChars = 22;
  
      // Get the current input value
      var inputText = input.value;
  
      // Update the character count
      charCount.innerText = inputText.length;
  
      // Trim the input if it exceeds the maximum length
      if (inputText.length > maxChars) {
          input.value = inputText.slice(0, maxChars);
          charCount.innerText = maxChars; // Update count to maxChars
      }
  } {% endcomment %}
  </script>

  {% endblock body %}

confessions/templates/confessions/cworking.html
{% extends "base.html" %}
{% block body %}
{% comment %} {% load humanize %}
{% load static %} {% endcomment %}

<style>

    p{
        font-size:12px!important;
        margin-bottom:0.5em!important;
    }

</style>


<div class="container">

	<div class="">
		<div class="h-100 p-2 bg-body-tertiary border rounded-3" style=''>
		  <h6 style="text-align:center;">How Confessios Works</h6>
          <div>

		  <p class="" style="font-size:14px; margin-top:0.5em; line-height:2em;">
            1) You can confess anything to anyone in a completely anonymous way and can tag them so that the taggie can recieve a notification from mystranger.in that someone has confessed this about them and can respond back to it.
          </p>

		  <p class="" style="font-size:14px; margin-top:0.5em; line-height:2em;">
            2) Only the Taggie and You (confesser) can reply on your confession.  Everyone else can comment with a prefix "stranger".
          </p>

		  <p class="" style="font-size:14px; margin-top:0.5em; line-height:2em;">
            3) No other user can see your name or taggie's name, everyones identity is completely anonymous.
          </p>
		  <p class="" style="font-size:14px; margin-top:0.5em; line-height:2em;">
            4) The confesser and taggie both have the ability to delete the confession
          </p>
		  <p class="" style="font-size:14px; margin-top:0.5em; line-height:2em;">
            5) Anonymity comes with a responsibility so please don't spread any hate speech that violates the indian law. as long as you follow the indian law it's fine otherwise if someone files a complaint against you then we will be forced to share your information. so please just don't break the law. as long as you follow that it's fine.
          </p>
          <a class="btn btn-sm btn-primary" href="{% url "confessions:pikac" %}" style="font-size:12px;">return to confessions</a>
        </div>

        </div>
    </div>
</div>

{% endblock body %}

confessions/templates/confessions/qnaroom.html
{% extends "base.html" %}
{% block body %}

<h1>This is the question and answer view</h1>

{% endblock body %}